const LIKE_TWEET = "LIKE_TWEET"
const UNLIKE_TWEET = "UNLIKE_TWEET"
const CREATE_TWEET = "CREATE_TWEET"
const OPEN_TWEET = "OPEN_TWEET"
const DELETE_TWEET = "DELETE_TWEET"
const OPEN_MODAL = "OPEN_MODAL"

export {
    LIKE_TWEET,
    UNLIKE_TWEET,
    CREATE_TWEET,
    OPEN_TWEET,
    DELETE_TWEET,
    OPEN_MODAL,
}